### ISSUE TITLE
hello, 我有一个问题

### ISSUE THREAD

**Issue by J-DuYa** [xiaosa233/we_assist#1]
我最近想用itchat写一个获取聊天信息的接口，看了你的我download下来 但是运行你的代码，发现还是我到官网看文档写代码，运行的那个错误： “ 为了你的帐号安全，此微信号不能登录网页微信。...”你有这个警告吗？或者有什么好的解决办法吗

**Comment by xiaosa233** [comment]
微信限制了这个微信号的web 网页登陆。原因可能是 这个微信用的时间不长/不活跃/资料少/被举报过 等原因。Anyway ，这是官方封了此微信号的web 登陆权限，基本无解

**Comment by xiaosa233** [comment]
> 我最近想用itchat写一个获取聊天信息的接口，看了你的我download下来 但是运行你的代码，发现还是我到官网看文档写代码，运行的那个错误： “ 为了你的帐号安全，此微信号不能登录网页微信。...”你有这个警告吗？或者有什么好的解决办法吗



> 我最近想用itchat写一个获取聊天信息的接口，看了你的我download下来 但是运行你的代码，发现还是我到官网看文档写代码，运行的那个错误： “ 为了你的帐号安全，此微信号不能登录网页微信。...”你有这个警告吗？或者有什么好的解决办法吗
