### ISSUE TITLE
这是什么问题

### ISSUE THREAD

**Issue by bigfool-cn** [xiaosa233/we_assist#4]
Your wechat account may be LIMITED to log in WEB wechat, error info:
<error><ret>1203</ret><message>为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>
Start auto replying.

**Comment by xiaosa233** [comment]
有些微信账号不能登录网页端

**Comment by xiaosa233** [comment]
基本没有解决方案

**Comment by xiaosa233** [comment]
https://zhuanlan.zhihu.com/p/76180564
